# Data settings
data:
  train_path: "C:/Users/Dell/PycharmProjects/ArabicNLP/data/raw/arabic_Depression_15.000_Tweets_Annotated.xlsx"

  test_size: 0.2
  random_state: 42
  processed_dir: "C:/Users/Dell/PycharmProjects/ArabicNLP/data/processed"
  token_file : "tokens.json"
  vocab_file: "vocab.json"
# Preprocessing
preprocessing:
  vocab_size: 1000
  min_word_length: 2
  remove_stopwords: true

# Embeddings
embeddings:
  embed_dim: 50
  window_size: 2
  num_negatives: 5
  epochs: 5
  batch_size: 512
  learning_rate: 0.01
  embedding_output: "data/embeddings/word2vec_50d.npy"   # <- make sure this exists

# Feature extraction
features:
  method: "embedding"  # statistical, embedding, tfidf_weighted, combined
  pooling: "mean"      # mean, max, sum, weighted
  use_pca: true
  pca_dims: 30

# Model
model:
  type: "logistic_regression"
  max_iter: 1000

