{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 05 - Model Training and Hyperparameter Tuning\n",
    "This notebook covers:\n",
    "- Training multiple classification models\n",
    "- Hyperparameter tuning with Grid/Random Search\n",
    "- Cross-validation\n",
    "- Model comparison and selection"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import pickle\n",
    "import json\n",
    "from pathlib import Path\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, cross_val_score\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.metrics import classification_report, confusion_matrix, accuracy_score\n",
    "from sklearn.metrics import precision_recall_fscore_support, roc_auc_score\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Set style\n",
    "sns.set_style('whitegrid')\n",
    "plt.rcParams['figure.figsize'] = (12, 6)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Load Processed Features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the features from previous notebook\n",
    "X_train = np.load('../data/processed/X_train_features.npy')\n",
    "X_test = np.load('../data/processed/X_test_features.npy')\n",
    "y_train = np.load('../data/processed/y_train.npy')\n",
    "y_test = np.load('../data/processed/y_test.npy')\n",
    "\n",
    "print(f\"Training set: {X_train.shape}\")\n",
    "print(f\"Test set: {X_test.shape}\")\n",
    "print(f\"Classes: {np.unique(y_train)}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Baseline Models\n",
    "Train quick baseline models to establish performance benchmarks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_baseline_models(X_train, y_train, X_test, y_test):\n",
    "    \"\"\"\n",
    "    Train baseline models with default parameters\n",
    "    \"\"\"\n",
    "    models = {\n",
    "        'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),\n",
    "        'Naive Bayes': MultinomialNB(),\n",
    "        'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),\n",
    "        'SVM': SVC(kernel='linear', random_state=42),\n",
    "        'Gradient Boosting': GradientBoostingClassifier(random_state=42)\n",
    "    }\n",
    "    \n",
    "    results = {}\n",
    "    \n",
    "    for name, model in models.items():\n",
    "        print(f\"\\nTraining {name}...\")\n",
    "        model.fit(X_train, y_train)\n",
    "        \n",
    "        # Predictions\n",
    "        y_pred = model.predict(X_test)\n",
    "        \n",
    "        # Metrics\n",
    "        accuracy = accuracy_score(y_test, y_pred)\n",
    "        precision, recall, f1, _ = precision_recall_fscore_support(\n",
    "            y_test, y_pred, average='weighted'\n",
    "        )\n",
    "        \n",
    "        results[name] = {\n",
    "            'model': model,\n",
    "            'accuracy': accuracy,\n",
    "            'precision': precision,\n",
    "            'recall': recall,\n",
    "            'f1': f1,\n",
    "            'predictions': y_pred\n",
    "        }\n",
    "        \n",
    "        print(f\"Accuracy: {accuracy:.4f}\")\n",
    "        print(f\"F1 Score: {f1:.4f}\")\n",
    "    \n",
    "    return results\n",
    "\n",
    "baseline_results = train_baseline_models(X_train, y_train, X_test, y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Compare baseline models\n",
    "baseline_df = pd.DataFrame({\n",
    "    'Model': list(baseline_results.keys()),\n",
    "    'Accuracy': [r['accuracy'] for r in baseline_results.values()],\n",
    "    'Precision': [r['precision'] for r in baseline_results.values()],\n",
    "    'Recall': [r['recall'] for r in baseline_results.values()],\n",
    "    'F1 Score': [r['f1'] for r in baseline_results.values()]\n",
    "})\n",
    "\n",
    "baseline_df = baseline_df.sort_values('F1 Score', ascending=False)\n",
    "print(\"\\n=== Baseline Model Comparison ===\")\n",
    "print(baseline_df.to_string(index=False))\n",
    "\n",
    "# Visualize\n",
    "fig, ax = plt.subplots(1, 1, figsize=(10, 6))\n",
    "baseline_df.set_index('Model')[['Accuracy', 'Precision', 'Recall', 'F1 Score']].plot(\n",
    "    kind='bar', ax=ax\n",
    ")\n",
    "ax.set_title('Baseline Model Performance Comparison')\n",
    "ax.set_ylabel('Score')\n",
    "ax.set_ylim([0, 1])\n",
    "ax.legend(loc='lower right')\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Hyperparameter Tuning\n",
    "Tune the top performing models using Grid Search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define parameter grids for top models\n",
    "param_grids = {\n",
    "    'Logistic Regression': {\n",
    "        'C': [0.001, 0.01, 0.1, 1, 10, 100],\n",
    "        'penalty': ['l1', 'l2'],\n",
    "        'solver': ['liblinear', 'saga'],\n",
    "        'max_iter': [1000]\n",
    "    },\n",
    "    'Random Forest': {\n",
    "        'n_estimators': [100, 200, 300],\n",
    "        'max_depth': [10, 20, 30, None],\n",
    "        'min_samples_split': [2, 5, 10],\n",
    "        'min_samples_leaf': [1, 2, 4],\n",
    "        'max_features': ['sqrt', 'log2']\n",
    "    },\n",
    "    'SVM': {\n",
    "        'C': [0.1, 1, 10, 100],\n",
    "        'kernel': ['linear', 'rbf'],\n",
    "        'gamma': ['scale', 'auto']\n",
    "    },\n",
    "    'Gradient Boosting': {\n",
    "        'n_estimators': [100, 200, 300],\n",
    "        'learning_rate': [0.01, 0.05, 0.1],\n",
    "        'max_depth': [3, 5, 7],\n",
    "        'subsample': [0.8, 0.9, 1.0]\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def tune_model(model, param_grid, X_train, y_train, model_name, cv=5):\n",
    "    \"\"\"\n",
    "    Perform grid search with cross-validation\n",
    "    \"\"\"\n",
    "    print(f\"\\n{'='*50}\")\n",
    "    print(f\"Tuning {model_name}...\")\n",
    "    print(f\"{'='*50}\")\n",
    "    \n",
    "    grid_search = GridSearchCV(\n",
    "        model,\n",
    "        param_grid,\n",
    "        cv=cv,\n",
    "        scoring='f1_weighted',\n",
    "        n_jobs=-1,\n",
    "        verbose=1\n",
    "    )\n",
    "    \n",
    "    grid_search.fit(X_train, y_train)\n",
    "    \n",
    "    print(f\"\\nBest parameters: {grid_search.best_params_}\")\n",
    "    print(f\"Best CV F1 score: {grid_search.best_score_:.4f}\")\n",
    "    \n",
    "    return grid_search\n",
    "\n",
    "# Tune models (this may take a while)\n",
    "tuned_models = {}\n",
    "\n",
    "# Logistic Regression\n",
    "lr_grid = tune_model(\n",
    "    LogisticRegression(random_state=42),\n",
    "    param_grids['Logistic Regression'],\n",
    "    X_train, y_train,\n",
    "    'Logistic Regression'\n",
    ")\n",
    "tuned_models['Logistic Regression'] = lr_grid.best_estimator_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Random Forest (use RandomizedSearchCV for faster tuning)\n",
    "from sklearn.model_selection import RandomizedSearchCV\n",
    "\n",
    "rf_random = RandomizedSearchCV(\n",
    "    RandomForestClassifier(random_state=42),\n",
    "    param_grids['Random Forest'],\n",
    "    n_iter=20,\n",
    "    cv=5,\n",
    "    scoring='f1_weighted',\n",
    "    n_jobs=-1,\n",
    "    verbose=1,\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "print(\"\\nTuning Random Forest (Randomized Search)...\")\n",
    "rf_random.fit(X_train, y_train)\n",
    "print(f\"Best parameters: {rf_random.best_params_}\")\n",
    "print(f\"Best CV F1 score: {rf_random.best_score_:.4f}\")\n",
    "\n",
    "tuned_models['Random Forest'] = rf_random.best_estimator_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# SVM\n",
    "svm_grid = tune_model(\n",
    "    SVC(random_state=42),\n",
    "    param_grids['SVM'],\n",
    "    X_train, y_train,\n",
    "    'SVM'\n",
    ")\n",
    "tuned_models['SVM'] = svm_grid.best_estimator_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Gradient Boosting (use RandomizedSearchCV)\n",
    "gb_random = RandomizedSearchCV(\n",
    "    GradientBoostingClassifier(random_state=42),\n",
    "    param_grids['Gradient Boosting'],\n",
    "    n_iter=20,\n",
    "    cv=5,\n",
    "    scoring='f1_weighted',\n",
    "    n_jobs=-1,\n",
    "    verbose=1,\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "print(\"\\nTuning Gradient Boosting (Randomized Search)...\")\n",
    "gb_random.fit(X_train, y_train)\n",
    "print(f\"Best parameters: {gb_random.best_params_}\")\n",
    "print(f\"Best CV F1 score: {gb_random.best_score_:.4f}\")\n",
    "\n",
    "tuned_models['Gradient Boosting'] = gb_random.best_estimator_"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Evaluate Tuned Models"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def evaluate_tuned_models(models, X_test, y_test):\n",
    "    \"\"\"\n",
    "    Evaluate all tuned models on test set\n",
    "    \"\"\"\n",
    "    results = {}\n",
    "    \n",
    "    for name, model in models.items():\n",
    "        print(f\"\\nEvaluating {name}...\")\n",
    "        \n",
    "        # Predictions\n",
    "        y_pred = model.predict(X_test)\n",
    "        \n",
    "        # Metrics\n",
    "        accuracy = accuracy_score(y_test, y_pred)\n",
    "        precision, recall, f1, _ = precision_recall_fscore_support(\n",
    "            y_test, y_pred, average='weighted'\n",
    "        )\n",
    "        \n",
    "        # Per-class metrics\n",
    "        report = classification_report(y_test, y_pred, output_dict=True)\n",
    "        \n",
    "        results[name] = {\n",
    "            'model': model,\n",
    "            'accuracy': accuracy,\n",
    "            'precision': precision,\n",
    "            'recall': recall,\n",
    "            'f1': f1,\n",
    "            'predictions': y_pred,\n",
    "            'report': report\n",
    "        }\n",
    "        \n",
    "        print(f\"Accuracy: {accuracy:.4f}\")\n",
    "        print(f\"F1 Score: {f1:.4f}\")\n",
    "    \n",
    "    return results\n",
    "\n",
    "tuned_results = evaluate_tuned_models(tuned_models, X_test, y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Compare tuned vs baseline\n",
    "comparison_data = []\n",
    "\n",
    "for model_name in tuned_models.keys():\n",
    "    comparison_data.append({\n",
    "        'Model': model_name,\n",
    "        'Type': 'Baseline',\n",
    "        'F1 Score': baseline_results[model_name]['f1'],\n",
    "        'Accuracy': baseline_results[model_name]['accuracy']\n",
    "    })\n",
    "    comparison_data.append({\n",
    "        'Model': model_name,\n",
    "        'Type': 'Tuned',\n",
    "        'F1 Score': tuned_results[model_name]['f1'],\n",
    "        'Accuracy': tuned_results[model_name]['accuracy']\n",
    "    })\n",
    "\n",
    "comparison_df = pd.DataFrame(comparison_data)\n",
    "\n",
    "# Visualize improvement\n",
    "fig, axes = plt.subplots(1, 2, figsize=(15, 5))\n",
    "\n",
    "for idx, metric in enumerate(['F1 Score', 'Accuracy']):\n",
    "    pivot_df = comparison_df.pivot(index='Model', columns='Type', values=metric)\n",
    "    pivot_df.plot(kind='bar', ax=axes[idx])\n",
    "    axes[idx].set_title(f'{metric} - Baseline vs Tuned')\n",
    "    axes[idx].set_ylabel(metric)\n",
    "    axes[idx].set_ylim([0, 1])\n",
    "    axes[idx].legend(title='Type')\n",
    "    axes[idx].set_xticklabels(axes[idx].get_xticklabels(), rotation=45, ha='right')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Cross-Validation Analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Perform k-fold cross-validation on best models\n",
    "cv_results = {}\n",
    "\n",
    "for name, model in tuned_models.items():\n",
    "    print(f\"\\nCross-validating {name}...\")\n",
    "    scores = cross_val_score(\n",
    "        model, X_train, y_train,\n",
    "        cv=5,\n",
    "        scoring='f1_weighted',\n",
    "        n_jobs=-1\n",
    "    )\n",
    "    cv_results[name] = scores\n",
    "    print(f\"CV F1 Scores: {scores}\")\n",
    "    print(f\"Mean: {scores.mean():.4f} (+/- {scores.std() * 2:.4f})\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Visualize CV scores\n",
    "fig, ax = plt.subplots(figsize=(10, 6))\n",
    "\n",
    "cv_df = pd.DataFrame(cv_results)\n",
    "cv_df.boxplot(ax=ax)\n",
    "ax.set_title('Cross-Validation F1 Scores Distribution')\n",
    "ax.set_ylabel('F1 Score')\n",
    "ax.set_xlabel('Model')\n",
    "plt.xticks(rotation=45, ha='right')\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Select Best Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Find best model based on F1 score\n",
    "best_model_name = max(tuned_results.items(), key=lambda x: x[1]['f1'])[0]\n",
    "best_model = tuned_results[best_model_name]['model']\n",
    "\n",
    "print(f\"\\n{'='*50}\")\n",
    "print(f\"BEST MODEL: {best_model_name}\")\n",
    "print(f\"{'='*50}\")\n",
    "print(f\"\\nTest Set Performance:\")\n",
    "print(f\"Accuracy: {tuned_results[best_model_name]['accuracy']:.4f}\")\n",
    "print(f\"Precision: {tuned_results[best_model_name]['precision']:.4f}\")\n",
    "print(f\"Recall: {tuned_results[best_model_name]['recall']:.4f}\")\n",
    "print(f\"F1 Score: {tuned_results[best_model_name]['f1']:.4f}\")\n",
    "\n",
    "print(f\"\\nDetailed Classification Report:\")\n",
    "print(classification_report(\n",
    "    y_test,\n",
    "    tuned_results[best_model_name]['predictions']\n",
    "))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Save Best Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create results directory\n",
    "results_dir = Path('../results/models')\n",
    "results_dir.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Save best model\n",
    "model_path = results_dir / 'best_model.pkl'\n",
    "with open(model_path, 'wb') as f:\n",
    "    pickle.dump(best_model, f)\n",
    "print(f\"\\nBest model saved to: {model_path}\")\n",
    "\n",
    "# Save all tuned models\n",
    "for name, model in tuned_models.items():\n",
    "    model_file = results_dir / f\"{name.replace(' ', '_').lower()}.pkl\"\n",
    "    with open(model_file, 'wb') as f:\n",
    "        pickle.dump(model, f)\n",
    "    print(f\"Saved {name} to: {model_file}\")\n",
    "\n",
    "# Save results metadata\n",
    "metadata = {\n",
    "    'best_model': best_model_name,\n",
    "    'best_f1_score': float(tuned_results[best_model_name]['f1']),\n",
    "    'best_accuracy': float(tuned_results[best_model_name]['accuracy']),\n",
    "    'all_models': {\n",
    "        name: {\n",
    "            'f1': float(res['f1']),\n",
    "            'accuracy': float(res['accuracy']),\n",
    "            'precision': float(res['precision']),\n",
    "            'recall': float(res['recall'])\n",
    "        }\n",
    "        for name, res in tuned_results.items()\n",
    "    }\n",
    "}\n",
    "\n",
    "with open(results_dir / 'model_results.json', 'w', encoding='utf-8') as f:\n",
    "    json.dump(metadata, f, indent=2, ensure_ascii=False)\n",
    "\n",
    "print(\"\\nModel training complete!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
